name = "linkie"
main = "src/index.js"
compatibility_date = "2023-09-14"
routes = [
  { pattern = "s.aly.pet", custom_domain = true }
]
kv_namespaces = [
  { binding = "KV", id = "7214e776a3da4ccd9f9fe5b6c3d3f781" }
]
[vars]
REDIR_URL = "https://aly-smith.carrd.co/"
