on:
  repository_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@master
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          secrets: |
              AUTH_KEY
        env:
            CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
            AUTH_KEY: ${{ secrets.AUTH_KEY }}
